site_name: Inventa One - FORMAZIONE L1 STARTUP 
site_url: https://ivanrobuschi-custom.github.io/Inventa_One/
site_author: Ivan Robuschi
theme:
  name: material
  logo: assets/icons/logo.png
  favicon: assets/icons/favicon.png
  language: it
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.prune
    - navigation.indexes
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
plugins:
  - search
  - tags

copyright: Copyright Custom S.p.A 2026

nav:
  - Inventa One:
      - Home: index.md
  - Caratteristiche software:
      - Architettura software: architettura_software.md
      - Caratteristiche licenze moduli:
        - Modulo Principale: modulo_principale.md
        - Modulo Horeca: modulo_horeca.md
  - Prima Installazione:
        - Download e Requisiti: download_e_requisiti.md
        - Gestione Licenze: gestione_licenze.md
  - Installazione software:
        - Installazione Windows: installazione_windows.md
        - Installazione Linux: installazione_linux.md
        - Installazione MacOS: installazione_macos.md
        - Installazione Android: installazione_android.md
  - Gestione Aggiornamenti:
        - Automatici: agg_automatici.md
        - Manuali: agg_manuali.md
  - Installazione guidata:
      - Seleziona modalità di utilizzo: selezione_modalita_utilizzo.md
      - Scelta Layout:
        - Nuovo Layout: nuovo_layout.md
        - Importa Backup: importa_backup.md
  - Configurazione dispositivo RT: 
      - Configurazione RT Custom: configurazione_rt_custom.md
  - Configuraizione Backup:
      - Backup locale: backup_locale.md
      - Backup ftp: backup_ftp.md
  - Configurazioni di base:
      - Creazione e gestione REPARTO: creazione_e_gestione_reparto.md
      - Creazione e gestione ARTICOLI: creazione_e_gestione_articoli.md
  - Emissione primo documento commerciale:
      - DC con pagamento contante: dc_con_pagamento_contante.md
      - DC con pagamento elettronico: dc_con_pagamento_elettronico.md


   
